apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-app
  name: frontend-app-service
  namespace: e-34
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend-app
  type: NodePort
status:
  loadBalancer: {}
